services:
  web-app:
    image: ${IMAGE_TAG:-ghcr.io/nikhilchakravarthy1303/vehicle-ai-platform/vehicle-ai-app:latest}
    build: .
    ports:
      - "8000:8000"
    
    # 💡 Docker will automatically search for and load this file from your host machine
    env_file:
      - .env.dev
      
    volumes:
      - vehicle-db:/app/data
      - vehicle-logs:/app/logs

volumes:
  vehicle-db:
  vehicle-logs: